# vim: ft=ruby

brew 'fish'
brew 'git'
brew 'node'
brew 'reattach-to-user-namespace'
brew 'stow'
brew 'tmux'
brew 'tree'
brew 'vim', args: ['with-lua', 'with-override-system-vi']

cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'hammerspoon'
cask 'iterm2'
cask 'java'
cask 'mplayerx'
cask 'shady'
cask 'slack'
cask 'sublime-text'
cask 'telegram'
cask 'transmission'
cask 'whatsapp'

tap 'caskroom/fonts'
cask 'font-fira-mono'
cask 'font-inconsolata'
cask 'font-input'
cask 'font-lato'
cask 'font-league-gothic'
cask 'font-lobster'
cask 'font-m-plus'
cask 'font-raleway'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
