#!/bin/bash

# Install Xcode Command-Line Tools
if ! xcode-select -p ; then
	xcode-select --install
	exit 0
fi

# Install homebrew
which brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew doctor || exit $?

# Install tools
brew install \
	axel \
	diff-so-fancy \
	fish \
	git \
	python \
	reattach-to-user-namespace \
	ruby \
	stow \
	vim
brew install --HEAD tmux

# Make fish the default shell
if ! grep fish /etc/shells; then
	echo '/usr/local/bin/fish' | sudo tee -a /etc/shells
	chsh -s /usr/local/bin/fish
fi

# Clone dotfiles
[ -d ~/.files ] || git clone https://github.com/spinningarrow/.files ~/.files

# Install dotfiles
pushd ~/.files
ls -d */ | xargs stow
popd

# Create ~/bin
[ -d ~/bin ] || mkdir ~/bin

# Install GUI apps
brew cask install \
	atom \
	dropbox \
	firefox \
	franz \
	google-chrome \
	iterm2 \
	java \
	mplayerx \
	shady \
	spectacle \
	sublime-text \
	telegram \
	texts \
	transmission
