#!/bin/bash

# Open terminal with theme so it can be set as default
terminalProfile=$(osascript -e 'tell application "Terminal" to get name of default settings')
test "$terminalProfile" = "Tomorrow Night Bright" || open ./Tomorrow\ Night\ Bright.terminal

# Install Xcode Command-Line Tools
if ! xcode-select -p ; then
	xcode-select --install
	exit 0
fi

# Install homebrew
which brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew doctor || exit $?

# Install command line tools
brew bundle -v

# Make fish the default shell
if ! grep fish /etc/shells; then
	echo '/usr/local/bin/fish' | sudo tee -a /etc/shells
fi

finger $USER | grep fish || chsh -s /usr/local/bin/fish

# Install dotfiles
[ -d ~/.files ] || git clone https://github.com/spinningarrow/.files ~/.files

# Create fish config directories to prevent stow from taking over .config
mkdir -p ~/.config/fish/functions

# Install dotfiles
pushd ~/.files
ls -d */ | xargs stow
popd

# For custom scripts to be availabe in $PATH
[ -d ~/bin ] || mkdir ~/bin

# Install GUI tools and fonts
brew bundle -v --file=Brewfile.casks
